### ISSUE TITLE
Prevent players from skipping their turn

### ISSUE THREAD

**Issue by KenDJohnson** [JHU-601/flask-production#49]
I could be wrong, but it looks like this isn't valid.

> Each hallway only holds one person. If someone is currently in a hallway, you may not move there.
> * When it is your turn, you don’t need to roll a die.
> * Your options of moving are limited to the following:
> * If you are in a room, you may do one of the following:
>     * Move through one of the doors to the hallway (if it is not blocked).
>     * Take a secret passage to a diagonally opposite room (if there is one) and make a suggestion.
>     * If you were moved to the room by another player making a suggestion, you may, if you wish, stay in that room and make a suggestion. Otherwise you may move through a doorway or take a secret passage as described above.

So it seems that you have to move unless you can't, or you were called to the current location.

Does this sound right?

If so, we need to add validation for this on both the client and server.

**Comment by stephengrice** [comment]
I don't think so. I interpret "When it is your turn, you don’t need to roll a die." as meaning you don't have to move. All of the statements regarding moving are "may" which seems to imply that it is optional.

However, that's just based on the wording that you pasted. Since they also said "The rules are pretty much the same except for moving from room to room" - maybe that includes the rule about having to move? I looked up the actual clue rules, and they require you to move.

I guess it comes down to the statement "When it is your turn, you don’t need to roll a die.". Does the professor mean:

* You don't have to physically roll a die. Rather, just move once.

OR

* You do not have to move at all on that turn.

Do you think it's worth asking the profs before we go through the effort of implementing? If so, I'll ask now. They promise a response within "up to a day" on the office hours, if I recall. We could have an answer by our Friday meeting.

Edit: I realize this is a bit of a rambling reply - sorry 😄

**Comment by KenDJohnson** [comment]
Yeah pretty sure we have to require a move. 

> I don't think so. I interpret "When it is your turn, you don’t need to roll a die." as meaning you don't have to move. 

That's just that there is no virtual die roll, from the simplification of the board layout where hallways are only one space. In the classic Clue game, hallways have a bunch of spaces in them and you roll a die to see how many spaces you can move.

**Comment by KevinKYeh** [comment]
In which case the only way you cannot move is if you're in a non-corner room and the 3/4 adjacent hallways are all occupied correct?
